# create new user
POST http://{{host}}:{{port}}/users
Content-Type: application/json

{
  "name": "user",
  "email": "test@test.com",
  "password": "qwerty"
}
###

# get all users
GET http://{{host}}:{{port}}/users
Accept: application/json
###

# get user by id
GET http://{{host}}:{{port}}/users/id/1
Accept: application/json
###

# get user by name
GET http://{{host}}:{{port}}/users/name/user
Accept: application/json
###

# update user by id
PUT http://{{host}}:{{port}}/users/1
Content-Type: application/json

{
  "name": "user1",
  "email": "test2@test.com",
  "password": "12345678"
}
###

# delete user by id
DELETE http://{{host}}:{{port}}/users/1
Content-Type: application/json
###

