# create new user
POST http://localhost:{{port}}/users
Content-Type: application/json

{
  "name": "user",
  "email": "test@test.com",
  "password": "qwerty"
}
###

# get all users
GET http://localhost:{{port}}/users
Accept: application/json
###

# get user by id
GET http://localhost:{{port}}/users/id/1
Accept: application/json
###

# get user by name
GET http://localhost:{{port}}/users/name/user
Accept: application/json
###

# update user by id
PUT http://localhost:{{port}}/users/1
Content-Type: application/json

{
  "name": "user1",
  "email": "test2@test.com",
  "password": "12345678"
}
###

# delete user by id
DELETE http://localhost:{{port}}/users/1
Content-Type: application/json
###

